on:
  pull_request:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

env:
  CMAKE_C_COMPILER_LAUNCHER: ccache
  CMAKE_CXX_COMPILER_LAUNCHER: ccache

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          audio_analyser
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - run: flutter pub get

      - name: Generate code
        run: dart run build_runner build

      - name: Analyze
        run: flutter analyze

  flutter-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          audio_analyser
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - run: flutter pub get

      - name: Format
        run: dart format -o none --set-exit-if-changed lib test

  flutter-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          audio_analyser
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - run: flutter pub get

      - name: Generate code
        run: dart run build_runner build

      - name: Test
        run: flutter test
